version: '3'

services:
  web:
    build: .
    command: python app.py
    ports:
      - "80:5000"
    volumes:
      - .:/code
    container_name: main_service

networks:
 default:
  external:
   name: ws_bridge
