version: '3'

services:
  web:
    build: .
    command: python app.py
    ports:
      - "80:5000"
    links:
      - "paulius_service"
    depends_on:
      - paulius_service
    volumes:
      - .:/code
    networks:
      - ws_bridge

  paulius_service:
    build: .
    command: python PauliusService/app.py
    ports:
      - 5001:5001
    networks:
      - ws_bridge

networks:
   ws_bridge:
